name: fixed
version: 5.3.0
homepage: https://github.com/onepub-dev/fixed
documentation: https://fixed.onepub.dev
description: Fixed scale decimal numbers with mathematical operations, formatting and parsing.
repository: https://github.com/onepub-dev/fixed
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  decimal: ^3.0.2
  intl: ^0.19.0
  meta: ^1.9.0
dev_dependencies:
  lint_hard: ^5.0.0
  test: ^1.16.0

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
