name: fixed
version: 2.4.0
homepage: https://github.com/onepub-dev/fixed
documentation: https://fixed.onepub.dev
description: Fixed scale decimal numbers with mathematical operations, formatting and parsing.
repository: https://github.com/onepub-dev/fixed
environment: 
  sdk: '>=2.14.0 <3.0.0'
dependencies: 
  decimal: ^2.3.0
  intl: ^0.18.0
  meta: ^1.9.0
dev_dependencies: 
  lint_hard: ^1.0.0
  test: ^1.16.0
