name: fixed
version: 2.2.1
homepage: https://github.com/onepub-dev/fixed
documentation: https://fixed.onepub.dev
description: Fixed scale decimal numbers with mathematical operations, formatting and parsing.
repository: https://github.com/onepub-dev/fixed
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  decimal: ^2.2.0
  intl: ^0.17.0
dev_dependencies: 
  lints: ^2.0.0
  test: ^1.16.0
